# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: audio_processor.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'audio_processor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x61udio_processor.proto\x12\x08speecheq\"\xe3\x02\n\x12ProcessingSettings\x12\x17\n\x0fnoise_reduction\x18\x01 \x01(\x08\x12\x13\n\x0bhum_removal\x18\x02 \x01(\x08\x12\x0f\n\x07\x64\x65\x65sser\x18\x03 \x01(\x08\x12\n\n\x02\x65q\x18\x04 \x01(\x08\x12\x15\n\rnormalization\x18\x05 \x01(\x08\x12\x1d\n\x15noise_reduction_level\x18\x06 \x01(\x02\x12\x15\n\rhum_frequency\x18\x07 \x01(\x02\x12\x1c\n\x14hum_removal_strength\x18\x08 \x01(\x02\x12\x18\n\x10\x64\x65\x65sser_strength\x18\t \x01(\x02\x12\x12\n\neq_profile\x18\n \x01(\t\x12\x1c\n\x14normalization_target\x18\x0b \x01(\x02\x12\x10\n\x08ml_model\x18\x0c \x01(\x08\x12\x15\n\rml_model_name\x18\r \x01(\t\x12\x13\n\x0bml_strength\x18\x0e \x01(\x02\x12\r\n\x05\x65xtra\x18\x0f \x01(\t\"\x93\x01\n\x0c\x41udioRequest\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\x12\x13\n\x0bsample_rate\x18\x02 \x01(\x05\x12.\n\x08settings\x18\x03 \x01(\x0b\x32\x1c.speecheq.ProcessingSettings\x12\x12\n\nrequest_id\x18\x04 \x01(\t\x12\x16\n\x0e\x63lient_version\x18\x05 \x01(\t\"d\n\rAudioResponse\x12\x17\n\x0fprocessed_audio\x18\x01 \x01(\x0c\x12\x15\n\rerror_message\x18\x02 \x01(\t\x12\x0f\n\x07success\x18\x03 \x01(\x08\x12\x12\n\nrequest_id\x18\x04 \x01(\t2S\n\x0e\x41udioProcessor\x12\x41\n\x0cProcessAudio\x12\x16.speecheq.AudioRequest\x1a\x17.speecheq.AudioResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'audio_processor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROCESSINGSETTINGS']._serialized_start=36
  _globals['_PROCESSINGSETTINGS']._serialized_end=391
  _globals['_AUDIOREQUEST']._serialized_start=394
  _globals['_AUDIOREQUEST']._serialized_end=541
  _globals['_AUDIORESPONSE']._serialized_start=543
  _globals['_AUDIORESPONSE']._serialized_end=643
  _globals['_AUDIOPROCESSOR']._serialized_start=645
  _globals['_AUDIOPROCESSOR']._serialized_end=728
# @@protoc_insertion_point(module_scope)
